name: Deploy Google Cloud Function and Scheduler

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy send_notifications \
            --runtime python39 \
            --trigger-http \
            --allow-unauthenticated \
            --region=us-central1 \
            --set-env-vars TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},CHAT_ID=${{ secrets.CHAT_ID }},API_URL=${{ secrets.API_URL }}

      - name: Get Cloud Function URL
        id: get_function_url
        run: |
          FUNCTION_URL=$(gcloud functions describe send_notifications --region=us-central1 --format="value(url)")
          echo "FUNCTION_URL=$FUNCTION_URL" >> $GITHUB_ENV

      - name: Create or Update Cloud Scheduler Job
        run: |
          gcloud scheduler jobs list --location=us-central1 --filter="name=trigger-notifications" --format="value(name)" | grep trigger-notifications \
          && gcloud scheduler jobs update http trigger-notifications \
            --location=us-central1 \
            --schedule="*/3 * * * *" \
            --uri=$FUNCTION_URL \
            --http-method=GET \
          || gcloud scheduler jobs create http trigger-notifications \
            --location=us-central1 \
            --schedule="*/3 * * * *" \
            --uri=$FUNCTION_URL \
            --http-method=GET

