name: Deploy Google Cloud Function and Scheduler

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy telegram_webhook \
            --runtime python39 \
            --trigger-http \
            --allow-unauthenticated \
            --region=us-central1 \
            --entry-point=telegram_webhook \
            --set-env-vars TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }},API_URL=${{ secrets.API_URL }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy send_notifications \
            --runtime python39 \
            --trigger-http \
            --allow-unauthenticated \
            --region=us-central1 \
            --entry-point=send_notifications \
            --set-env-vars TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }},API_URL=${{ secrets.API_URL }}

      - name: Get Cloud Function URL
        id: get_function_url
        run: |
          FUNCTION_URL=$(gcloud functions describe send_notifications --region=us-central1 --format="value(url)")
          echo "FUNCTION_URL=$FUNCTION_URL" >> $GITHUB_ENV

      - name: Create or Update Cloud Scheduler Job
        run: |
          if gcloud scheduler jobs describe trigger-notifications --location=us-central1 > /dev/null 2>&1; then
            echo "Job exists. Updating..."
            gcloud scheduler jobs update http trigger-notifications \
              --location=us-central1 \
              --schedule="* * * * *" \
              --uri=$FUNCTION_URL \
              --http-method=GET
          else
            echo "Job does not exist. Creating..."
            gcloud scheduler jobs create http trigger-notifications \
              --location=us-central1 \
              --schedule="* * * * *" \
              --uri=$FUNCTION_URL \
              --http-method=GET
          fi
        
      - name: Set Telegram Webhook
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/setWebhook" \
            -d "url=${{ env.FUNCTION_URL }}"



